apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: issdojmg2-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fae6d10695.e0uj.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:14707c6db90289d8927514c0763f3782c3e1edba@sha256:c244232762ac9c6802395ac1997cfa737a332efd94bf950c71359600ff463665
          name: container-image
